name: Optimized Deploy Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'terraform/**'
      - '.github/workflows/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: employee-frontend
  TERRAFORM_VERSION: 1.5.5

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init -input=false
          terraform apply -auto-approve -parallelism=10 \
            -var="ecr_repository_url=${{ secrets.ECR_URL }}"
          terraform output

  application:
    runs-on: ubuntu-latest
    needs: infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          platforms: linux/amd64

      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster employee-cluster \
            --service employee-frontend-service \
            --force-new-deployment \
            --output text

      - name: Wait for ECS Deployment
        run: |
          aws ecs wait services-stable \
            --cluster employee-cluster \
            --services employee-frontend-service
